### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by exldna** [carl-vbn/opengl-raytracing#1]
I open this project in VS22, try to build, but it's failed - compiler could not find some headers. Maybe you should to use any build systems like CMake.

**Comment by holasoyender** [comment]
Are you building on x86 or x64?

**Comment by exldna** [comment]
x64, Release version

**Comment by holasoyender** [comment]
Try running it on x86 Debug

**Comment by exldna** [comment]
okay, it's working

**Comment by carl-vbn** [comment]
Thanks for the assistance @holasoyender
